//! The format catalog: layouts (marker table + list definitions) per
//! elements.data version, and the named enum/flag sets their fields use.
//!
//! Built-in layouts live in `formats/layouts/<id>/`: a `layout.json` with the
//! marker table, and one `list_<n>.json` per defined list (generated by the
//! tools in `tools/`, embedded in the binary). Only list heads (name, struct,
//! size) are read at startup; fields are parsed when a list is first used.
//! The schema editor saves to the same structure in the app data folder,
//! where each file overrides that list of the built-in layout. Several layouts
//! may share a version number when server builds diverged; the reader picks
//! the one that fits the file best.

use std::collections::{BTreeMap, HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "k", rename_all = "lowercase")]
pub enum Ty {
    I8,
    U8,
    Bool,
    I16,
    U16,
    I32,
    U32,
    F32,
    F64,
    I64,
    U64,
    Wstr { n: usize },
    Str { n: usize },
    Bytes { n: usize },
    Array { n: usize, stride: usize, t: Box<Ty> },
    Struct { fields: Vec<Field> },
}

impl Ty {
    pub fn size(&self) -> usize {
        match self {
            Ty::I8 | Ty::U8 | Ty::Bool => 1,
            Ty::I16 | Ty::U16 => 2,
            Ty::I32 | Ty::U32 | Ty::F32 => 4,
            Ty::F64 | Ty::I64 | Ty::U64 => 8,
            Ty::Wstr { n } => n * 2,
            Ty::Str { n } | Ty::Bytes { n } => *n,
            Ty::Array { n, stride, .. } => n * stride,
            Ty::Struct { fields } => fields.iter().map(|f| f.off + f.t.size()).max().unwrap_or(0),
        }
    }

    pub fn label(&self) -> String {
        match self {
            Ty::I8 => "int8".into(),
            Ty::U8 => "uint8".into(),
            Ty::Bool => "bool".into(),
            Ty::I16 => "int16".into(),
            Ty::U16 => "uint16".into(),
            Ty::I32 => "int32".into(),
            Ty::U32 => "uint32".into(),
            Ty::F32 => "float".into(),
            Ty::F64 => "double".into(),
            Ty::I64 => "int64".into(),
            Ty::U64 => "uint64".into(),
            Ty::Wstr { n } => format!("wchar[{n}]"),
            Ty::Str { n } => format!("char[{n}]"),
            Ty::Bytes { n } => format!("byte[{n}]"),
            Ty::Array { n, t, .. } => format!("{}[{n}]", t.label()),
            Ty::Struct { .. } => "struct".into(),
        }
    }

    /// Checks offsets and strides: every field fits its struct, arrays have
    /// strides of at least their element size.
    fn check(&self, path: &str) -> Result<(), String> {
        match self {
            Ty::Wstr { n } | Ty::Str { n } | Ty::Bytes { n } if *n == 0 => Err(format!("{path}: length must be at least 1")),
            Ty::Array { n, stride, t } => {
                if *n == 0 {
                    return Err(format!("{path}: array length must be at least 1"));
                }
                if *stride < t.size() {
                    return Err(format!("{path}: array stride {stride} is smaller than its element ({} B)", t.size()));
                }
                t.check(path)
            }
            Ty::Struct { fields } => check_fields(fields, path),
            _ => Ok(()),
        }
    }
}

fn check_fields(fields: &[Field], path: &str) -> Result<(), String> {
    let mut names = HashSet::new();
    for f in fields {
        let here = if path.is_empty() { f.name.clone() } else { format!("{path}.{}", f.name) };
        if f.name.trim().is_empty() {
            return Err(format!("{path}: a field has no name"));
        }
        if !names.insert(f.name.as_str()) {
            return Err(format!("{here}: duplicate field name"));
        }
        f.t.check(&here)?;
        for rule in &f.when {
            if !fields.iter().any(|s| s.name == rule.field && s.name != f.name) {
                return Err(format!("{here}: a type rule refers to {:?}, which is not a field next to it", rule.field));
            }
            if rule.values.is_empty() {
                return Err(format!("{here}: a type rule has no values"));
            }
            if rule.t.size() != f.t.size() {
                return Err(format!("{here}: a type rule's type must be {} bytes like the field", f.t.size()));
            }
        }
    }
    Ok(())
}

fn is_false(b: &bool) -> bool {
    !b
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Field {
    pub name: String,
    pub off: usize,
    pub t: Ty,
    /// Comment (from the source header, or written in the schema editor).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub c: Option<String>,
    /// Key of an enum or mask (`formats/enums` or `formats/masks`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub e: Option<String>,
    /// How the value is meant to be read: "path", "icon" or "skill".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// Structs (e.g. "EQUIPMENT_ADDON") of the lists whose IDs this field holds.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub refs: Vec<String>,
    /// Display group: consecutive fields with the same group are shown
    /// together under one collapsible row. It does not affect the layout.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub g: Option<String>,
    /// Optional colour of this struct heading in the record inspector.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// Optional colour of the display group named by `g`. Repeated on its
    /// members because groups are not stored as fields of their own.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gc: Option<String>,
    /// Conditional types: the first rule whose sibling field matches decides
    /// how this field is read; otherwise `t` applies.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub when: Vec<TypeRule>,
}

/// "If sibling `field` is (not) one of `values`, read this field as `t`."
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TypeRule {
    pub field: String,
    #[serde(rename = "in")]
    pub values: Vec<i64>,
    #[serde(default, skip_serializing_if = "is_false")]
    pub not: bool,
    pub t: Ty,
}

impl TypeRule {
    pub fn matches(&self, value: i64) -> bool {
        self.values.contains(&value) != self.not
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListDef {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    pub name: String,
    #[serde(default, rename = "struct", skip_serializing_if = "Option::is_none")]
    pub struct_name: Option<String>,
    /// Record size the fields describe; absent for name-only definitions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<usize>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub fields: Vec<Field>,
}

impl ListDef {
    /// Validates a definition written in the schema editor.
    pub fn check(&self) -> Result<(), String> {
        if self.name.trim().is_empty() {
            return Err("The list needs a name".into());
        }
        check_fields(&self.fields, "")?;
        let extent = self.fields.iter().map(|f| f.off + f.t.size()).max().unwrap_or(0);
        match self.size {
            Some(size) if extent > size => Err(format!("Fields end at byte {extent}, past the declared size {size}")),
            None if !self.fields.is_empty() => Err("A definition with fields needs a size".into()),
            _ => Ok(()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MarkerKind {
    /// 8 bytes: one slice of the MD5 digest the client verifies.
    Checksum,
    /// u32 tag, u32 len, len bytes (exporter machine name), u32 time.
    Exporter,
    /// u32 tag, u32 len, len bytes.
    Tag,
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Marker {
    /// The list slot the marker precedes.
    pub before: usize,
    pub kind: MarkerKind,
}

/// A named set of values or bit flags.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EnumSet {
    #[serde(default)]
    pub label: String,
    /// Bit flags (keys are bit values) rather than plain values.
    #[serde(default)]
    pub flags: bool,
    pub items: HashMap<String, String>,
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub descriptions: HashMap<String, String>,
}

impl EnumSet {
    pub fn label_for(&self, value: i64) -> Option<String> {
        if !self.flags {
            return self.items.get(&value.to_string()).cloned();
        }
        let bits = value as u64;
        if bits == 0 {
            return Some("(none)".into());
        }
        let parts: Vec<String> = (0..64)
            .map(|b| 1u64 << b)
            .filter(|bit| bits & bit != 0)
            .map(|bit| self.items.get(&bit.to_string()).cloned().unwrap_or_else(|| format!("0x{bit:x}")))
            .collect();
        Some(parts.join(" | "))
    }
}

// ---------------------------------------------------------------- enums and masks

/// Enums name single values; masks name the bits of a bit field.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SetKind {
    Enum,
    Mask,
}

impl SetKind {
    pub fn folder(self) -> &'static str {
        match self {
            SetKind::Enum => "enums",
            SetKind::Mask => "masks",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EnumValue {
    pub value: i64,
    pub label: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MaskFlag {
    /// Bit index, 0 (value 1) … 63.
    pub bit: u32,
    pub label: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,
}

/// An enum or mask as stored in `formats/<enums|masks>/<key>.json`. Its kind
/// comes from the folder.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NamedSet {
    pub key: String,
    #[serde(default)]
    pub label: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub values: Vec<EnumValue>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub flags: Vec<MaskFlag>,
    /// In the user folder: hides the built-in set with this key.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub deleted: bool,
}

/// Keys name files and are referenced from fields: lowercase letters,
/// digits and underscores.
pub fn valid_set_key(key: &str) -> bool {
    !key.is_empty() && key.len() <= 64 && key.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
}

impl NamedSet {
    pub fn check(&self, kind: SetKind) -> Result<(), String> {
        if !valid_set_key(&self.key) {
            return Err(format!("The key {:?} may only use lowercase letters, digits and _", self.key));
        }
        if self.deleted {
            return Ok(());
        }
        let mut seen = HashSet::new();
        match kind {
            SetKind::Enum => {
                for v in &self.values {
                    if v.label.trim().is_empty() {
                        return Err(format!("Value {} needs a label", v.value));
                    }
                    if !seen.insert(v.value) {
                        return Err(format!("Value {} is listed twice", v.value));
                    }
                }
            }
            SetKind::Mask => {
                for f in &self.flags {
                    if f.bit > 63 {
                        return Err(format!("Bit {} is out of range (0–63)", f.bit));
                    }
                    if f.label.trim().is_empty() {
                        return Err(format!("Bit {} needs a label", f.bit));
                    }
                    if !seen.insert(f.bit as i64) {
                        return Err(format!("Bit {} is listed twice", f.bit));
                    }
                }
            }
        }
        Ok(())
    }

    /// The lookup form used when decoding.
    pub fn to_enum_set(&self, kind: SetKind) -> EnumSet {
        let mut items = HashMap::new();
        let mut descriptions = HashMap::new();
        match kind {
            SetKind::Enum => {
                for v in &self.values {
                    items.insert(v.value.to_string(), v.label.clone());
                    if !v.description.is_empty() {
                        descriptions.insert(v.value.to_string(), v.description.clone());
                    }
                }
            }
            SetKind::Mask => {
                for f in &self.flags {
                    let bit = (1u64 << f.bit).to_string();
                    items.insert(bit.clone(), f.label.clone());
                    if !f.description.is_empty() {
                        descriptions.insert(bit, f.description.clone());
                    }
                }
            }
        }
        EnumSet { label: self.label.clone(), flags: kind == SetKind::Mask, items, descriptions }
    }
}

/// Where a set in the catalog comes from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum SetOrigin {
    /// Built into the app.
    Builtin,
    /// A built-in set the user changed.
    Override,
    /// Created by the user.
    User,
    /// A built-in set the user deleted (hidden until restored).
    Deleted,
}

#[derive(Debug, Clone)]
pub struct SetEntry {
    pub kind: SetKind,
    pub set: NamedSet,
    pub origin: SetOrigin,
}

/// Everything the catalog needs about a list before its fields are parsed:
/// enough to pick a layout and align lists by size.
#[derive(Debug, Clone, Deserialize)]
pub struct ListHead {
    #[serde(default)]
    pub key: Option<String>,
    pub name: String,
    #[serde(default, rename = "struct")]
    pub struct_name: Option<String>,
    #[serde(default)]
    pub size: Option<usize>,
    /// Whether the definition has any fields (scanned, not parsed).
    #[serde(default, rename = "fields")]
    has_any_field: NonEmpty,
}

impl ListHead {
    fn of(def: &ListDef) -> Self {
        Self {
            key: def.key.clone(),
            name: def.name.clone(),
            struct_name: def.struct_name.clone(),
            size: def.size,
            has_any_field: NonEmpty(!def.fields.is_empty()),
        }
    }

    /// Curated layouts name lists they could not identify "UNKNOWN12" etc.
    pub fn is_placeholder(&self) -> bool {
        self.struct_name.as_deref().unwrap_or(&self.name).to_ascii_uppercase().starts_with("UNKNOWN")
    }

    pub fn has_fields(&self) -> bool {
        self.size.is_some() && self.has_any_field.0
    }
}

/// Deserializes a JSON array to "is it non-empty" while skipping its contents.
#[derive(Debug, Clone, Copy, Default)]
struct NonEmpty(bool);

impl<'de> Deserialize<'de> for NonEmpty {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        struct Visitor;
        impl<'de> serde::de::Visitor<'de> for Visitor {
            type Value = NonEmpty;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("an array")
            }
            fn visit_seq<A: serde::de::SeqAccess<'de>>(self, mut seq: A) -> Result<NonEmpty, A::Error> {
                let mut any = false;
                while seq.next_element::<serde::de::IgnoredAny>()?.is_some() {
                    any = true;
                }
                Ok(NonEmpty(any))
            }
        }
        d.deserialize_seq(Visitor)
    }
}

/// One list slot of a layout: its head, and the full definition parsed on
/// first use.
#[derive(Debug, Clone)]
pub struct ListSlot {
    pub head: ListHead,
    /// Embedded JSON of the definition, until it is parsed.
    source: Option<&'static str>,
    def: OnceLock<Option<ListDef>>,
}

impl ListSlot {
    fn lazy(json: &'static str) -> Result<Self, String> {
        let head = serde_json::from_str(json).map_err(|e| e.to_string())?;
        Ok(Self { head, source: Some(json), def: OnceLock::new() })
    }

    pub fn of(def: ListDef) -> Self {
        Self { head: ListHead::of(&def), source: None, def: OnceLock::from(Some(def)) }
    }

    pub fn def(&self) -> Option<&ListDef> {
        self.def
            .get_or_init(|| {
                serde_json::from_str(self.source?)
                    .map_err(|e| eprintln!("list definition could not be parsed: {e}"))
                    .ok()
            })
            .as_ref()
    }
}

/// `layout.json`: a layout without its list definitions.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LayoutMeta {
    pub id: String,
    pub version: u32,
    pub source: String,
    pub markers: Vec<Marker>,
    /// Number of list slots (definitions are optional per slot).
    pub list_count: usize,
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub enums: HashMap<String, EnumSet>,
    /// The list count was not checked against a real file.
    #[serde(default, skip_serializing_if = "is_false")]
    pub list_count_unverified: bool,
}

#[derive(Debug, Clone)]
pub struct Layout {
    pub id: String,
    pub version: u32,
    pub source: String,
    pub markers: Vec<Marker>,
    /// List slots; `None` where the list is not defined.
    pub lists: Vec<Option<ListSlot>>,
    pub enums: HashMap<String, EnumSet>,
    pub list_count_unverified: bool,
}

impl Layout {
    fn from_meta(meta: LayoutMeta) -> Self {
        Self {
            id: meta.id,
            version: meta.version,
            source: meta.source,
            markers: meta.markers,
            lists: vec![None; meta.list_count],
            enums: meta.enums,
            list_count_unverified: meta.list_count_unverified,
        }
    }

    fn set_slot(&mut self, index: usize, slot: ListSlot) {
        if self.lists.len() <= index {
            self.lists.resize(index + 1, None);
        }
        self.lists[index] = Some(slot);
    }

    pub fn head(&self, index: usize) -> Option<&ListHead> {
        Some(&self.lists.get(index)?.as_ref()?.head)
    }

    /// The full definition of a list slot (parsed on first use).
    pub fn list(&self, index: usize) -> Option<&ListDef> {
        self.lists.get(index)?.as_ref()?.def()
    }
}

pub struct Catalog {
    pub layouts: Vec<Arc<Layout>>,
    /// Enums and masks by key, for decoding.
    pub enums: HashMap<String, EnumSet>,
    /// The enums and masks themselves, by key, for the editor.
    pub sets: BTreeMap<String, SetEntry>,
    /// Built-in sets the user deleted, by key (for restoring them).
    pub deleted: BTreeMap<String, SetEntry>,
    /// (layout id, list slot) pairs defined by the user's schema files.
    pub user: HashSet<(String, usize)>,
    /// Layouts that exist only in the user folder.
    pub user_layouts: HashSet<String>,
    /// User layout files that could not be loaded.
    pub errors: Vec<String>,
}

static FORMATS: include_dir::Dir<'static> = include_dir::include_dir!("$CARGO_MANIFEST_DIR/formats");

const LAYOUT_FILE: &str = "layout.json";

/// Slot number of a `list_<n>.json` file name.
fn list_slot(file_name: &str) -> Option<usize> {
    file_name.strip_prefix("list_")?.strip_suffix(".json")?.parse().ok()
}

fn builtin_layouts() -> &'static [Arc<Layout>] {
    static LAYOUTS: OnceLock<Vec<Arc<Layout>>> = OnceLock::new();
    LAYOUTS.get_or_init(|| {
        let root = FORMATS.get_dir("layouts").expect("formats/layouts is embedded");
        let mut layouts: Vec<Arc<Layout>> = root
            .dirs()
            .filter_map(|dir| {
                let meta = dir.get_file(dir.path().join(LAYOUT_FILE))?;
                let meta: LayoutMeta = serde_json::from_str(meta.contents_utf8()?).expect("embedded layout.json is valid");
                let mut layout = Layout::from_meta(meta);
                for file in dir.files() {
                    let name = file.path().file_name().and_then(|n| n.to_str()).unwrap_or_default();
                    if let Some(index) = list_slot(name) {
                        let text = file.contents_utf8().expect("embedded list file is UTF-8");
                        layout.set_slot(index, ListSlot::lazy(text).expect("embedded list file is valid"));
                    }
                }
                Some(Arc::new(layout))
            })
            .collect();
        layouts.sort_by(|a, b| (a.version, &a.id).cmp(&(b.version, &b.id)));
        layouts
    })
}

fn builtin_sets() -> &'static BTreeMap<String, SetEntry> {
    static SETS: OnceLock<BTreeMap<String, SetEntry>> = OnceLock::new();
    SETS.get_or_init(|| {
        let mut sets = BTreeMap::new();
        for kind in [SetKind::Enum, SetKind::Mask] {
            let Some(dir) = FORMATS.get_dir(kind.folder()) else { continue };
            for file in dir.files() {
                let text = file.contents_utf8().expect("embedded set file is UTF-8");
                let set: NamedSet = serde_json::from_str(text).expect("embedded set file is valid");
                sets.insert(set.key.clone(), SetEntry { kind, set, origin: SetOrigin::Builtin });
            }
        }
        sets
    })
}

pub fn builtin_set(key: &str) -> Option<&'static SetEntry> {
    builtin_sets().get(key)
}

pub fn builtin_layout(id: &str) -> Option<&'static Arc<Layout>> {
    builtin_layouts().iter().find(|l| l.id == id)
}

/// A layout id is also a folder name, so keep it to safe characters.
pub fn valid_layout_id(id: &str) -> bool {
    !id.is_empty() && id.len() <= 64 && id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.')
}

impl Catalog {
    /// Built-in layouts and sets with the user's files laid over them. In
    /// `user_root/layouts/<id>/`, each `list_<n>.json` replaces that list of
    /// layout `<id>`, and a `layout.json` defines a layout with no built-in.
    /// `user_root/enums/<key>.json` and `masks/<key>.json` replace or add sets.
    pub fn load(user_root: Option<&Path>) -> Self {
        let user_dir = user_root.map(|r| r.join("layouts"));
        let user_dir = user_dir.as_deref();
        let mut layouts: Vec<Arc<Layout>> = builtin_layouts().to_vec();
        let mut user = HashSet::new();
        let mut user_layouts = HashSet::new();
        let mut errors = Vec::new();

        let folders = user_dir.and_then(|d| std::fs::read_dir(d).ok()).into_iter().flatten().flatten();
        for folder in folders.filter(|e| e.path().is_dir()) {
            let id = folder.file_name().to_string_lossy().into_owned();
            if !valid_layout_id(&id) {
                continue;
            }
            let mut layout = match layouts.iter().position(|l| l.id == id) {
                Some(i) => (*layouts.remove(i)).clone(),
                None => {
                    let meta = std::fs::read_to_string(folder.path().join(LAYOUT_FILE))
                        .map_err(|e| e.to_string())
                        .and_then(|s| serde_json::from_str::<LayoutMeta>(&s).map_err(|e| e.to_string()));
                    match meta {
                        Ok(meta) if meta.id == id => {
                            user_layouts.insert(id.clone());
                            Layout::from_meta(meta)
                        }
                        Ok(meta) => {
                            errors.push(format!("{}: layout.json has id {:?}", folder.path().display(), meta.id));
                            continue;
                        }
                        Err(e) => {
                            errors.push(format!("{}: {e}", folder.path().join(LAYOUT_FILE).display()));
                            continue;
                        }
                    }
                }
            };
            for file in std::fs::read_dir(folder.path()).into_iter().flatten().flatten() {
                let Some(index) = list_slot(&file.file_name().to_string_lossy()) else { continue };
                let parsed = std::fs::read_to_string(file.path())
                    .map_err(|e| e.to_string())
                    .and_then(|s| serde_json::from_str::<ListDef>(&s).map_err(|e| e.to_string()));
                match parsed {
                    Ok(def) => {
                        layout.set_slot(index, ListSlot::of(def));
                        user.insert((id.clone(), index));
                    }
                    Err(e) => errors.push(format!("{}: {e}", file.path().display())),
                }
            }
            layouts.push(Arc::new(layout));
        }

        layouts.sort_by(|a, b| (a.version, &a.id).cmp(&(b.version, &b.id)));

        // Enums and masks: built-in, then the user's files by key.
        let mut sets = builtin_sets().clone();
        let mut deleted = BTreeMap::new();
        for kind in [SetKind::Enum, SetKind::Mask] {
            let Some(dir) = user_root.map(|r| r.join(kind.folder())) else { continue };
            for file in std::fs::read_dir(&dir).into_iter().flatten().flatten() {
                let path = file.path();
                let Some(stem) = path.file_stem().and_then(|s| s.to_str()).filter(|_| path.extension().is_some_and(|e| e == "json")) else {
                    continue;
                };
                let parsed = std::fs::read_to_string(&path)
                    .map_err(|e| e.to_string())
                    .and_then(|s| serde_json::from_str::<NamedSet>(&s).map_err(|e| e.to_string()))
                    .and_then(|set| if set.key == stem { set.check(kind).map(|_| set) } else { Err(format!("key {:?} does not match the file name", set.key)) });
                let set = match parsed {
                    Ok(set) => set,
                    Err(e) => {
                        errors.push(format!("{}: {e}", path.display()));
                        continue;
                    }
                };
                let origin = match builtin_sets().get(&set.key) {
                    Some(b) if b.kind != kind => {
                        errors.push(format!("{}: {:?} is a built-in {}", path.display(), set.key, b.kind.folder().trim_end_matches('s')));
                        continue;
                    }
                    Some(b) if set.deleted => {
                        sets.remove(&set.key);
                        deleted.insert(set.key.clone(), SetEntry { origin: SetOrigin::Deleted, ..b.clone() });
                        continue;
                    }
                    // Nothing left to hide.
                    None if set.deleted => continue,
                    Some(_) => SetOrigin::Override,
                    None => SetOrigin::User,
                };
                sets.insert(set.key.clone(), SetEntry { kind, set, origin });
            }
        }
        let enums = sets.iter().map(|(k, e)| (k.clone(), e.set.to_enum_set(e.kind))).collect();

        Self { layouts, enums, sets, deleted, user, user_layouts, errors }
    }

    /// Fields in all layouts that use a set, as "v160 · #3 Equipment Essence · proc_type".
    pub fn set_usage(&self, key: &str) -> Vec<String> {
        fn walk(fields: &[Field], prefix: &str, key: &str, out: &mut Vec<String>) {
            for f in fields {
                let name = if prefix.is_empty() { f.name.clone() } else { format!("{prefix}.{}", f.name) };
                if f.e.as_deref() == Some(key) {
                    out.push(name.clone());
                }
                let mut t = &f.t;
                while let Ty::Array { t: inner, .. } = t {
                    t = inner;
                }
                if let Ty::Struct { fields } = t {
                    walk(fields, &name, key, out);
                }
            }
        }
        let mut out = Vec::new();
        for layout in &self.layouts {
            for (i, slot) in layout.lists.iter().enumerate() {
                let Some(slot) = slot.as_ref().filter(|s| s.head.has_fields()) else { continue };
                let Some(def) = slot.def() else { continue };
                let mut names = Vec::new();
                walk(&def.fields, "", key, &mut names);
                for n in names {
                    out.push(format!("{} · #{i} {} · {n}", layout.id, def.name));
                }
            }
        }
        out
    }

    pub fn find(&self, id: &str) -> Option<&Arc<Layout>> {
        self.layouts.iter().find(|l| l.id == id)
    }

    pub fn enum_set<'a>(&'a self, layout: Option<&'a Layout>, key: &str) -> Option<&'a EnumSet> {
        layout.and_then(|l| l.enums.get(key)).or_else(|| self.enums.get(key))
    }

    /// Distinct marker tables, nearest version first.
    pub fn marker_tables(&self, version: u32) -> Vec<&Arc<Layout>> {
        let mut layouts: Vec<&Arc<Layout>> = self.layouts.iter().collect();
        layouts.sort_by_key(|l| (l.version.abs_diff(version), l.id.clone()));
        let mut seen: Vec<Vec<(usize, MarkerKind)>> = Vec::new();
        layouts
            .into_iter()
            .filter(|l| {
                let key: Vec<_> = l.markers.iter().map(|m| (m.before, m.kind)).collect();
                let new = !seen.contains(&key);
                if new {
                    seen.push(key);
                }
                new
            })
            .collect()
    }
}

// ---------------------------------------------------------------- user schema files

fn write_atomic(path: &Path, contents: &str) -> Result<(), String> {
    let tmp = path.with_extension("json.tmp");
    std::fs::write(&tmp, contents).map_err(|e| format!("Could not write {}: {e}", tmp.display()))?;
    std::fs::rename(&tmp, path).map_err(|e| format!("Could not write {}: {e}", path.display()))
}

pub fn user_set_path(root: &Path, kind: SetKind, key: &str) -> PathBuf {
    root.join(kind.folder()).join(format!("{key}.json"))
}

/// Saves an enum or mask to `root/<enums|masks>/<key>.json`. A set identical
/// to the built-in one removes the user file instead.
pub fn save_user_set(root: &Path, kind: SetKind, set: &NamedSet) -> Result<(), String> {
    set.check(kind)?;
    if let Some(b) = builtin_set(&set.key) {
        if b.kind != kind {
            return Err(format!("{:?} is already a built-in {}", set.key, b.kind.folder().trim_end_matches('s')));
        }
        if b.set == *set {
            return delete_user_set(root, &set.key);
        }
    }
    let dir = root.join(kind.folder());
    std::fs::create_dir_all(&dir).map_err(|e| format!("Could not create {}: {e}", dir.display()))?;
    let json = serde_json::to_string_pretty(set).map_err(|e| e.to_string())? + "\n";
    write_atomic(&user_set_path(root, kind, &set.key), &json)
}

/// Deletes a set: a user set's file is removed, a built-in set is hidden by
/// a `{ key, deleted: true }` file (removing that file restores it).
pub fn delete_set(root: &Path, key: &str) -> Result<(), String> {
    let Some(b) = builtin_set(key) else { return delete_user_set(root, key) };
    delete_user_set(root, key)?;
    let tombstone = NamedSet { key: key.into(), label: String::new(), values: vec![], flags: vec![], deleted: true };
    let dir = root.join(b.kind.folder());
    std::fs::create_dir_all(&dir).map_err(|e| format!("Could not create {}: {e}", dir.display()))?;
    let json = serde_json::to_string_pretty(&tombstone).map_err(|e| e.to_string())? + "
";
    write_atomic(&user_set_path(root, b.kind, key), &json)
}

/// Removes the user's file for a set: a built-in set returns to its built-in
/// definition (also when it was deleted), a user set is deleted.
pub fn delete_user_set(root: &Path, key: &str) -> Result<(), String> {
    if !valid_set_key(key) {
        return Err(format!("Invalid key {key:?}"));
    }
    for kind in [SetKind::Enum, SetKind::Mask] {
        let path = user_set_path(root, kind, key);
        if path.exists() {
            std::fs::remove_file(&path).map_err(|e| format!("Could not remove {}: {e}", path.display()))?;
        }
    }
    Ok(())
}

pub fn user_list_path(dir: &Path, id: &str, list: usize) -> PathBuf {
    dir.join(id).join(format!("list_{list}.json"))
}

/// Saves one list definition as `dir/<id>/list_<n>.json`. `new_layout` is the
/// layout.json to write when the layout has no built-in or user folder yet.
/// A definition identical to the built-in one removes the user file instead.
pub fn save_user_list(dir: &Path, id: &str, list: usize, def: &ListDef, new_layout: Option<&LayoutMeta>) -> Result<(), String> {
    if !valid_layout_id(id) {
        return Err(format!("Invalid layout id {id:?}"));
    }
    if builtin_layout(id).and_then(|b| b.list(list)) == Some(def) {
        return delete_user_list(dir, id, list);
    }
    let folder = dir.join(id);
    std::fs::create_dir_all(&folder).map_err(|e| format!("Could not create {}: {e}", folder.display()))?;
    if let Some(meta) = new_layout {
        let path = folder.join(LAYOUT_FILE);
        if !path.exists() {
            write_atomic(&path, &serde_json::to_string_pretty(meta).map_err(|e| e.to_string())?)?;
        }
    }
    let json = serde_json::to_string_pretty(def).map_err(|e| e.to_string())? + "\n";
    write_atomic(&user_list_path(dir, id, list), &json)
}

/// Removes a user list file. A user-only layout left without lists is removed.
pub fn delete_user_list(dir: &Path, id: &str, list: usize) -> Result<(), String> {
    let path = user_list_path(dir, id, list);
    if path.exists() {
        std::fs::remove_file(&path).map_err(|e| format!("Could not remove {}: {e}", path.display()))?;
    }
    let folder = dir.join(id);
    let has_lists = std::fs::read_dir(&folder)
        .into_iter()
        .flatten()
        .flatten()
        .any(|e| list_slot(&e.file_name().to_string_lossy()).is_some());
    if !has_lists && folder.exists() && builtin_layout(id).is_none() {
        std::fs::remove_dir_all(&folder).map_err(|e| format!("Could not remove {}: {e}", folder.display()))?;
    } else if !has_lists && folder.exists() {
        // Only an empty overlay folder of a built-in layout is left.
        let _ = std::fs::remove_dir(&folder);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtins_load_lazily() {
        let t = std::time::Instant::now();
        let catalog = Catalog::load(None);
        eprintln!("catalog: {} layouts in {:?}", catalog.layouts.len(), t.elapsed());
        let v156 = catalog.find("v156").unwrap();
        assert_eq!(v156.lists.len(), 193);
        let slot = v156.lists[3].as_ref().unwrap();
        assert_eq!(slot.head.struct_name.as_deref(), Some("EQUIPMENT_ESSENCE"));
        assert!(slot.head.has_fields());
        // The built-ins are shared with tests running alongside, so check
        // laziness on a fresh slot of the same file.
        let json = FORMATS.get_file("layouts/v156/list_3.json").and_then(|f| f.contents_utf8()).unwrap();
        let fresh = ListSlot::lazy(json).unwrap();
        assert!(fresh.head.has_fields());
        assert!(fresh.def.get().is_none(), "fields are not parsed until used");
        assert_eq!(fresh.def().unwrap().size, Some(644));
        assert_eq!(v156.list(3).unwrap().size, Some(644));
        assert!(catalog.find("v66").unwrap().lists.iter().all(Option::is_none));
        // Enums and masks come from their folders.
        assert_eq!(catalog.sets["trade_behavior"].kind, SetKind::Mask);
        assert_eq!(catalog.sets["gender"].kind, SetKind::Enum);
        assert!(catalog.enums["trade_behavior"].flags);
        assert_eq!(catalog.sets["bool"].kind, SetKind::Enum);
        assert!(!catalog.sets.keys().any(|k| k.starts_with("v112_")));
    }

    #[test]
    fn user_sets_override_add_and_revert() {
        let root = std::env::temp_dir().join(format!("jdide-sets-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let mut gender = builtin_set("gender").unwrap().set.clone();
        gender.values.push(EnumValue { value: 9, label: "Test".into(), description: String::new() });
        save_user_set(&root, SetKind::Enum, &gender).unwrap();
        let mine = NamedSet { key: "my_flags".into(), label: "Mine".into(), values: vec![], flags: vec![MaskFlag { bit: 3, label: "Eight".into(), description: String::new() }], deleted: false };
        save_user_set(&root, SetKind::Mask, &mine).unwrap();
        // A key cannot change kind, and duplicates are rejected.
        assert!(save_user_set(&root, SetKind::Mask, &gender).is_err());
        let mut twice = mine.clone();
        twice.flags.push(twice.flags[0].clone());
        assert!(save_user_set(&root, SetKind::Mask, &twice).is_err());

        let catalog = Catalog::load(Some(&root));
        assert_eq!(catalog.sets["gender"].origin, SetOrigin::Override);
        assert_eq!(catalog.enums["gender"].label_for(9).as_deref(), Some("Test"));
        assert_eq!(catalog.sets["my_flags"].origin, SetOrigin::User);
        assert_eq!(catalog.enums["my_flags"].label_for(8).as_deref(), Some("Eight"));
        assert!(!catalog.set_usage("trade_behavior").is_empty());

        // Saving the built-in definition again, or deleting, reverts.
        save_user_set(&root, SetKind::Enum, &builtin_set("gender").unwrap().set).unwrap();
        delete_user_set(&root, "my_flags").unwrap();
        let catalog = Catalog::load(Some(&root));
        assert_eq!(catalog.sets["gender"].origin, SetOrigin::Builtin);
        assert!(!catalog.sets.contains_key("my_flags"));

        // Deleting a built-in hides it until reverted.
        delete_set(&root, "gender").unwrap();
        let catalog = Catalog::load(Some(&root));
        assert!(catalog.errors.is_empty(), "{:?}", catalog.errors);
        assert!(!catalog.sets.contains_key("gender") && !catalog.enums.contains_key("gender"));
        assert_eq!(catalog.deleted["gender"].origin, SetOrigin::Deleted);
        delete_user_set(&root, "gender").unwrap();
        assert_eq!(Catalog::load(Some(&root)).sets["gender"].origin, SetOrigin::Builtin);
        let _ = std::fs::remove_dir_all(&root);
    }
}
