//! The format catalog: layouts (marker table + list definitions) per
//! elements.data version, and the named enum/flag sets their fields use.
//!
//! Layouts live in `formats/layouts/*.json` and are generated by the tools in
//! `tools/`. Several layouts may share a version number when server builds
//! diverged; the reader picks the one that fits the file best.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "k", rename_all = "lowercase")]
pub enum Ty {
    I8,
    U8,
    Bool,
    I16,
    U16,
    I32,
    U32,
    F32,
    F64,
    I64,
    U64,
    Wstr { n: usize },
    Str { n: usize },
    Bytes { n: usize },
    Array { n: usize, stride: usize, t: Box<Ty> },
    Struct { fields: Vec<Field> },
}

impl Ty {
    pub fn size(&self) -> usize {
        match self {
            Ty::I8 | Ty::U8 | Ty::Bool => 1,
            Ty::I16 | Ty::U16 => 2,
            Ty::I32 | Ty::U32 | Ty::F32 => 4,
            Ty::F64 | Ty::I64 | Ty::U64 => 8,
            Ty::Wstr { n } => n * 2,
            Ty::Str { n } | Ty::Bytes { n } => *n,
            Ty::Array { n, stride, .. } => n * stride,
            Ty::Struct { fields } => fields.iter().map(|f| f.off + f.t.size()).max().unwrap_or(0),
        }
    }

    pub fn label(&self) -> String {
        match self {
            Ty::I8 => "int8".into(),
            Ty::U8 => "uint8".into(),
            Ty::Bool => "bool".into(),
            Ty::I16 => "int16".into(),
            Ty::U16 => "uint16".into(),
            Ty::I32 => "int32".into(),
            Ty::U32 => "uint32".into(),
            Ty::F32 => "float".into(),
            Ty::F64 => "double".into(),
            Ty::I64 => "int64".into(),
            Ty::U64 => "uint64".into(),
            Ty::Wstr { n } => format!("wchar[{n}]"),
            Ty::Str { n } => format!("char[{n}]"),
            Ty::Bytes { n } => format!("byte[{n}]"),
            Ty::Array { n, t, .. } => format!("{}[{n}]", t.label()),
            Ty::Struct { .. } => "struct".into(),
        }
    }
}

#[derive(Debug, Clone, Deserialize)]
pub struct Field {
    pub name: String,
    pub off: usize,
    pub t: Ty,
    /// Comment from the source header.
    #[serde(default)]
    pub c: Option<String>,
    /// Key of an enum/flag set (layout-local or in `enums.json`).
    #[serde(default)]
    pub e: Option<String>,
    /// How the value is meant to be read: "path", "icon" or "skill".
    #[serde(default)]
    pub display: Option<String>,
    /// Structs (e.g. "EQUIPMENT_ADDON") of the lists whose IDs this field holds.
    #[serde(default)]
    pub refs: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ListDef {
    #[serde(default)]
    pub key: Option<String>,
    pub name: String,
    #[serde(default, rename = "struct")]
    pub struct_name: Option<String>,
    /// Record size the fields describe; absent for name-only definitions.
    #[serde(default)]
    pub size: Option<usize>,
    #[serde(default)]
    pub fields: Vec<Field>,
}

impl ListDef {
    /// Curated layouts name lists they could not identify "UNKNOWN12" etc.
    pub fn is_placeholder(&self) -> bool {
        self.struct_name.as_deref().unwrap_or(&self.name).to_ascii_uppercase().starts_with("UNKNOWN")
    }

    pub fn has_fields(&self) -> bool {
        self.size.is_some() && !self.fields.is_empty()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MarkerKind {
    /// 8 bytes: one slice of the MD5 digest the client verifies.
    Checksum,
    /// u32 tag, u32 len, len bytes (exporter machine name), u32 time.
    Exporter,
    /// u32 tag, u32 len, len bytes.
    Tag,
}

#[derive(Debug, Clone, Copy, Deserialize)]
pub struct Marker {
    /// The list slot the marker precedes.
    pub before: usize,
    pub kind: MarkerKind,
}

/// A named set of values or bit flags. (The JSON may also carry a label and
/// per-item descriptions; the reader does not use them yet.)
#[derive(Debug, Clone, Deserialize)]
pub struct EnumSet {
    /// Bit flags (keys are bit values) rather than plain values.
    #[serde(default)]
    pub flags: bool,
    pub items: HashMap<String, String>,
}

impl EnumSet {
    pub fn label_for(&self, value: i64) -> Option<String> {
        if !self.flags {
            return self.items.get(&value.to_string()).cloned();
        }
        let bits = value as u64;
        if bits == 0 {
            return Some("(none)".into());
        }
        let parts: Vec<String> = (0..64)
            .map(|b| 1u64 << b)
            .filter(|bit| bits & bit != 0)
            .map(|bit| self.items.get(&bit.to_string()).cloned().unwrap_or_else(|| format!("0x{bit:x}")))
            .collect();
        Some(parts.join(" | "))
    }
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Layout {
    pub id: String,
    pub version: u32,
    pub source: String,
    pub markers: Vec<Marker>,
    /// List definitions by slot; `null` where the list is not known.
    pub lists: Vec<Option<ListDef>>,
    #[serde(default)]
    pub enums: HashMap<String, EnumSet>,
    /// The layout's list count was not checked against a real file.
    #[serde(default)]
    pub list_count_unverified: bool,
}

impl Layout {
    pub fn list(&self, index: usize) -> Option<&ListDef> {
        self.lists.get(index)?.as_ref()
    }
}

pub struct Catalog {
    pub layouts: Vec<Layout>,
    pub enums: HashMap<String, EnumSet>,
}

impl Catalog {
    pub fn enum_set<'a>(&'a self, layout: &'a Layout, key: &str) -> Option<&'a EnumSet> {
        layout.enums.get(key).or_else(|| self.enums.get(key))
    }

    /// Distinct marker tables, nearest version first.
    pub fn marker_tables(&self, version: u32) -> Vec<&Layout> {
        let mut layouts: Vec<&Layout> = self.layouts.iter().collect();
        layouts.sort_by_key(|l| (l.version.abs_diff(version), l.id.clone()));
        let mut seen: Vec<Vec<(usize, MarkerKind)>> = Vec::new();
        layouts
            .into_iter()
            .filter(|l| {
                let key: Vec<_> = l.markers.iter().map(|m| (m.before, m.kind)).collect();
                let new = !seen.contains(&key);
                if new {
                    seen.push(key);
                }
                new
            })
            .collect()
    }
}

static LAYOUT_SOURCES: &[&str] = &[
    include_str!("../../formats/layouts/v66.json"),
    include_str!("../../formats/layouts/v112.json"),
    include_str!("../../formats/layouts/v156.json"),
    include_str!("../../formats/layouts/v156-signin.json"),
    include_str!("../../formats/layouts/v158.json"),
    include_str!("../../formats/layouts/v160.json"),
    include_str!("../../formats/layouts/v165.json"),
    include_str!("../../formats/layouts/v176.json"),
];

static ENUMS_SOURCE: &str = include_str!("../../formats/enums.json");

pub fn catalog() -> &'static Catalog {
    static CATALOG: OnceLock<Catalog> = OnceLock::new();
    CATALOG.get_or_init(|| Catalog {
        layouts: LAYOUT_SOURCES
            .iter()
            .map(|src| serde_json::from_str(src).expect("embedded layout is valid"))
            .collect(),
        enums: serde_json::from_str(ENUMS_SOURCE).expect("embedded enums are valid"),
    })
}
