//! Format profiles: list names and record layouts for a given elements.data
//! version. Generated by `tools/gen-elements-schema.mjs` (from the server
//! template sources) and `tools/import-jade-editor-profile.mjs`.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "k", rename_all = "lowercase")]
pub enum Ty {
    I8,
    U8,
    Bool,
    I16,
    U16,
    I32,
    U32,
    F32,
    F64,
    I64,
    U64,
    Wstr { n: usize },
    Str { n: usize },
    Bytes { n: usize },
    Array { n: usize, stride: usize, t: Box<Ty> },
    Struct { fields: Vec<Field> },
}

impl Ty {
    pub fn size(&self) -> usize {
        match self {
            Ty::I8 | Ty::U8 | Ty::Bool => 1,
            Ty::I16 | Ty::U16 => 2,
            Ty::I32 | Ty::U32 | Ty::F32 => 4,
            Ty::F64 | Ty::I64 | Ty::U64 => 8,
            Ty::Wstr { n } => n * 2,
            Ty::Str { n } | Ty::Bytes { n } => *n,
            Ty::Array { n, stride, .. } => n * stride,
            Ty::Struct { fields } => fields.iter().map(|f| f.off + f.t.size()).max().unwrap_or(0),
        }
    }

    pub fn label(&self) -> String {
        match self {
            Ty::I8 => "int8".into(),
            Ty::U8 => "uint8".into(),
            Ty::Bool => "bool".into(),
            Ty::I16 => "int16".into(),
            Ty::U16 => "uint16".into(),
            Ty::I32 => "int32".into(),
            Ty::U32 => "uint32".into(),
            Ty::F32 => "float".into(),
            Ty::F64 => "double".into(),
            Ty::I64 => "int64".into(),
            Ty::U64 => "uint64".into(),
            Ty::Wstr { n } => format!("wchar[{n}]"),
            Ty::Str { n } => format!("char[{n}]"),
            Ty::Bytes { n } => format!("byte[{n}]"),
            Ty::Array { n, t, .. } => format!("{}[{n}]", t.label()),
            Ty::Struct { .. } => "struct".into(),
        }
    }
}

#[derive(Debug, Clone, Deserialize)]
pub struct Field {
    pub name: String,
    pub off: usize,
    pub t: Ty,
    /// Comment from the source header.
    #[serde(default)]
    pub c: Option<String>,
    /// Name of an enum in `Profile::enums`.
    #[serde(default)]
    pub e: Option<String>,
    /// The enum is a bit mask.
    #[serde(default)]
    pub flags: bool,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ListDef {
    #[serde(default)]
    pub key: Option<String>,
    pub name: String,
    #[serde(default, rename = "struct")]
    pub struct_name: Option<String>,
    #[serde(default)]
    pub size: Option<usize>,
    #[serde(default)]
    pub fields: Vec<Field>,
}

#[derive(Debug, Deserialize)]
pub struct Profile {
    pub version: u32,
    pub source: String,
    /// Marker signature (see `ElementsFile::layout_signature`).
    pub layout: Option<String>,
    #[serde(default)]
    pub enums: HashMap<String, HashMap<String, String>>,
    pub lists: Vec<ListDef>,
}

impl Profile {
    pub fn enum_label(&self, name: &str, value: i64, flags: bool) -> Option<String> {
        let values = self.enums.get(name)?;
        if !flags {
            return values.get(&value.to_string()).cloned();
        }
        if value == 0 {
            return Some("(none)".into());
        }
        let bits = value as u64 & 0xffff_ffff;
        let parts: Vec<String> = (0..32)
            .filter(|b| bits & (1 << b) != 0)
            .map(|b| {
                let bit = 1u64 << b;
                values.get(&bit.to_string()).cloned().unwrap_or_else(|| format!("0x{bit:x}"))
            })
            .collect();
        Some(parts.join(" | "))
    }
}

static PROFILE_SOURCES: &[&str] = &[
    include_str!("../../profiles/v112.json"),
    include_str!("../../profiles/v156.json"),
];

pub fn profiles() -> &'static [Profile] {
    static PROFILES: OnceLock<Vec<Profile>> = OnceLock::new();
    PROFILES.get_or_init(|| {
        PROFILE_SOURCES
            .iter()
            .map(|src| serde_json::from_str(src).expect("embedded profile is valid JSON"))
            .collect()
    })
}

pub struct ProfileMatch {
    pub profile: &'static Profile,
    /// The profile was generated for exactly this version.
    pub exact: bool,
}

/// Picks the profile for a file: the exact version if available, otherwise the
/// nearest version whose list grouping (layout signature) is identical, since
/// newer files only append lists and grow structs.
pub fn select(version: u32, layout: &str) -> Option<ProfileMatch> {
    let all = profiles();
    if let Some(profile) = all.iter().find(|p| p.version == version) {
        return Some(ProfileMatch { profile, exact: true });
    }
    all.iter()
        .filter(|p| p.layout.as_deref() == Some(layout))
        .min_by_key(|p| p.version.abs_diff(version))
        .map(|profile| ProfileMatch { profile, exact: false })
}
